---
# tasks file for nginx-role
- name: Download nginx
  ansible.builtin.get_url:
    url: "https://nginx.org/packages/centos/7/x86_64/RPMS/nginx-{{ nginx_version }}.el7.ngx.x86_64.rpm"
    dest: "./nginx-{{ nginx_version }}.el7.ngx.x86_64.rpm"
- name: install nginx and git
  become: true
  ansible.builtin.yum:
    name: 
      - nginx-{{ nginx_version }}.el7.ngx.x86_64.rpm
- name: copy config nginx
  become: true
  template:
    src: "templates/default.conf"
    dest: "/etc/nginx/conf.d/default.conf"
  notify: Start nginx
- name: Delete default site
  become: true
  ansible.builtin.shell: "rm -rf /usr/share/nginx/html/*"